version: "3.3"
services:
  pxe-server:
    image: pxe-uefi
    container_name: pxe-uefi-container
    tty: true
    restart: always
    environment:
      - PXE_IP=192.168.20.3
      - PXE_SUBNET=192.168.20.0
      - PXE_GATEWAY=192.168.20.1
      - PXE_BROADCAST=192.168.20.255
      - PXE_NETMASK=255.255.255.0
      - PXE_RANGE_LOW=192.168.20.10
      - PXE_RANGE_HIGH=192.168.20.100
    networks:
      macnet:
        ipv4_address: 192.168.20.3 #Next ip after your ethernet current ip.
    volumes:
      - /home/ahmed/pxe_docker/packages:/packages #should be changed to your .deb packages directory
      - /images:/images #should be changed to your .iso images directory
networks:
  macnet:
    driver: macvlan
    driver_opts:
      parent: enp3s0
    ipam:
      config:
        - subnet: "192.168.20.0/24"
# pw for booted machine is evastel
# - sudo wget -O apache2.deb http://192.168.20.3/packages/apacheds-2.0.0.AM26-amd64.deb && sudo dpkg -i apache2.deb && sudo systemctl start apache2
